# Generated by Django 6.0 on 2026-04-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_preview',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
    ]
