# Generated by Django 6.0 on 2026-04-15 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_video_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='product',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Upload a high-quality PDF or image file.', null=True, upload_to='product_previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='digital_products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dwg', 'dxf', 'zip', 'pdf', 'rvt'])]),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g., Electrical Plan, Site Plan', max_length=100)),
                ('file', models.FileField(upload_to='product_gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_files', to='store.product')),
            ],
        ),
    ]
