# Generated by Django 6.0 on 2026-01-12 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('investor_type', models.CharField(choices=[('ANGEL', 'Angel Investor'), ('VC', 'Venture Capital'), ('INST', 'Institutional'), ('PARTNER', 'Partner')], max_length=10)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('is_accredited', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('HOUSE', 'House'), ('LAND', 'Land'), ('UNIT', 'Unit / Duplex'), ('APARTMENT', 'Apartment'), ('HOTEL', 'Hotel / Motel Room'), ('VILLAGE', 'Village / Workforce Accom')], default='HOUSE', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bond', models.IntegerField(blank=True, default=0)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0, verbose_name='Car Spaces')),
                ('sqft', models.IntegerField(default=0, verbose_name='Building Size (sqft)')),
                ('lot_size', models.DecimalField(decimal_places=1, default=0.0, max_digits=8, verbose_name='Land Size (sqm)')),
                ('furnished_status', models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Partly Furnished', 'Partly Furnished'), ('Fully Furnished', 'Fully Furnished')], default='Unfurnished', max_length=20)),
                ('proximity_to_center', models.CharField(blank=True, help_text="e.g. '5 min walk to CBD'", max_length=100)),
                ('total_units', models.IntegerField(default=1, verbose_name='Total Units in Complex')),
                ('vacant_units', models.IntegerField(default=0, verbose_name='Units Currently Available')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('RENTAL', 'Rentals'), ('SALE', 'For Sale'), ('CRISIS', 'Crisis Housing')], default='RENTAL', max_length=20)),
                ('is_pet_friendly', models.BooleanField(default=False, verbose_name='Is Pet Friendly?')),
                ('expectations', models.TextField(blank=True, default='Standard residential maintenance applies.')),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Who is eligible to apply?')),
                ('next_inspection', models.DateTimeField(blank=True, null=True)),
                ('inspection_booking_url', models.URLField(blank=True)),
                ('tier', models.CharField(choices=[('TIER1', 'Tier 1: Standard (DIY)'), ('TIER2', 'Tier 2: Village/Motel (Daily Mgmt)'), ('TIER3', 'Tier 3: Premium (Assisted)')], default='TIER1', max_length=10)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
