# Generated by Django 6.0 on 2026-01-27 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='next_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tier',
            field=models.CharField(choices=[('Basic', 'Tier 1: Basic ($99)'), ('Premium', 'Tier 2: Premium ($149)'), ('Platinum', 'Tier 3: Platinum ($299)')], default='Basic', max_length=20),
        ),
    ]
