# Generated by Django 6.0 on 2025-12-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('RENTAL', 'Rentals'), ('SALE', 'For Sale'), ('CRISIS', 'Crisis Housing')], default='SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Only for Crisis Housing'),
        ),
    ]
