# Generated by Django 6.0 on 2026-01-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_list_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='eligibility_criteria',
            field=models.TextField(blank=True),
        ),
    ]
