# Generated by Django 6.0 on 2026-02-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_eligibility_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tier',
            field=models.CharField(choices=[('Standard', 'Standard (DIY) - $99'), ('Manager', 'Manager Subscription - $199/mo'), ('FullService', 'Full Service - $550')], default='Basic', max_length=20),
        ),
    ]
