# Generated by Django 6.0 on 2025-12-28 11:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_category_listing_eligibility_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor_phone',
            field=models.CharField(blank=True, default='04XX XXX XXX', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('RENTAL', 'Rentals'), ('SALE', 'For Sale'), ('CRISIS', 'Crisis Housing')], default='RENTAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
