# Generated by Django 6.0 on 2025-12-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_photo_1_listing_realtor_phone_listing_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bond',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='expectations',
            field=models.TextField(blank=True, default='Standard residential maintenance applies.', help_text='General expectations for tenants/buyers'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_pet_friendly',
            field=models.BooleanField(default=False, verbose_name='is Pet friendly?'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
