# Generated by Django 6.0 on 2025-12-30 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_bond_listing_expectations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Is Pet Friendly?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
