# Generated by Django 6.0 on 2026-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_is_pet_friendly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='eligibility_criteria',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='tier',
            field=models.CharField(choices=[('TIER1', 'Tier 1: Standard (DIY)'), ('TIER2', 'Tier 2: Village/Motel (Daily Mgmt)'), ('TIER3', 'Tier 3: Premium (Assisted)')], default='TIER1', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_units',
            field=models.IntegerField(default=1, help_text='Total rooms/cabins (Tier 2 only)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vacant_units',
            field=models.IntegerField(default=0, help_text='How many are free right now? (Tier 2 only)'),
        ),
    ]
