# Generated by Django 6.0 on 2026-01-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_eligibility_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Company or Family Office name', max_length=100)),
                ('investor_type', models.CharField(choices=[('ANGEL', 'Angel Investor / Private Individual'), ('VC', 'Venture Capital Firm'), ('INST', 'Institutional Investor'), ('PARTNER', 'Strategic Partner / Media')], max_length=10)),
                ('linkedin_profile', models.URLField(blank=True, help_text='Optional: Helps us verify your profile')),
                ('is_accredited', models.BooleanField(default=False, verbose_name='I confirm I am a sophisticated/accredited investor')),
                ('message', models.TextField(blank=True, help_text='Tell us briefly about your investment focus.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
