# Generated by Django 5.2 on 2026-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification email to you went through.",
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(
                        default=False, help_text="Tick once you've replied."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="InvestorLead",
        ),
    ]
